### ISSUE TITLE
Major Bug: tsyganenko model not working

### ISSUE THREAD

**Issue by asreimer** [vtsuperdarn/davitpy#100]
While randomly testing different bits of davitpy I discovered that somewhere we lost the ability for the tsyganenko model to work properly. This bug affects the develop branch and the master branch! @sdelarquier since you worked on this implementing this model in davitpy can you help out with this bug please?

Here's the code I used to discover the bug:

    from numpy import arange, zeros, ones
    from models import tsyganenko
    lats = arange(10, 90, 10)
    lons = zeros(len(lats))
    rhos = 6372.*ones(len(lats))
    trace = tsyganenko.tsygTrace(lats, lons, rhos,datetime=datetime(2014,9,17,12))
    ax = trace.plot()

Notice that this code should produce a plot of the Earth's dipolar field on the +X GSM side of the Earth. Instead I get something like this:
![figure_1](https://cloud.githubusercontent.com/assets/4604819/4312055/ce338800-3eb5-11e4-8093-5e7bb7691d5f.png)
Something is very wrong here and I'm not exactly sure what is going on.

**Comment by johncoxon** [comment]
Was this ever resolved? If not, is there a timeframe on which it could be?

I am getting results from the Tsyganenko model in davitpy which I just don't believe (magnetopause is apparently at 2 RE, which is not sensible). I installed davitpy entirely because it implements T96, so this is rather critical functionality from my perspective….

**Comment by johncoxon** [comment]
I have just installed @sdelarquier's standalone Tsyganenko module, and found that I get values that I don't believe from the code there as well as from DaViTPy. [I have filed a bug report outlining these issues](https://github.com/sdelarquier/tsyganenko/issues/1).

(I've not done any Tsyganenko model work before, but I'm fairly confident that the output is wrong, and that this is due to the same bug.)

**Comment by asreimer** [comment]
This bug has now finally been fixed in #141. Fixed by commit d88bfae!

**Comment by sdelarquier** [comment]
Thanks @asreimer, you rock!
