### ISSUE TITLE
Problem with Rti mag plotting

### ISSUE THREAD

**Issue by guohucn** [vtsuperdarn/davitpy#120]
Hey, guys. I am new here, and not familiar with davitpy.
I'v got a problem as follows:
input:
  t1=dt.datetime(2013,3,17,11,50)
  t2=dt.datetime(2013,3,17,14,0)
  fig=pydarn.plotting.rti.plotRti(t1,'cvw',t2,bmnum=4,params=['velocity'],coords='mag')
output:

![figure_1](https://cloud.githubusercontent.com/assets/9592043/4938007/7bd09082-65c8-11e4-8664-0ecb8716d429.png)

It looks like the data above 52 degrees are cut off. There should be a SAPS.
Everything is OK if I use geo as coords. 
![figure_2](https://cloud.githubusercontent.com/assets/9592043/4938644/ece7fb1c-65cc-11e4-86e3-8bb350e2b873.png)
I use the develop branch. The master branch is even worse.  
By the way. The month in the title and the time along X-axis are incorrect. This is also a minor problem. 
Thanks!

**Comment by asreimer** [comment]
This is now fixed in #149. The problem was the beam 4 of CVE increases and then decreases in magnetic latitude. This means that when plotting as a function of mlat, the far range gates without data in them were getting plotted as white squares on top of the data at nearer range gates.

I fixed this bug by masking range gates without data in them and then using the `set_bad` method on the colormap to set the alpha to 0 for the "bad" (masked) range gates. This allows us to still use the speed of pcolormesh for plotting.

**Comment by MuhammadVT** [comment]
Hi Ashton,

I tested that the bug in #120
<https://github.com/vtsuperdarn/davitpy/issues/120>has been fixed by this
pull request.

A very minor issue is that it looks like the function arguments in the doc
strings are not matching the corresponding functions' arguments quite well,
and the examples are not updated, for example, the doc strings of
plot_skynoise, plot_searchnoise, plot_freq, etc.  Would you mind going
through the doc strings one more time?

Also, the argument fmt in line 750
<https://github.com/vtsuperdarn/davitpy/pull/149/files#diff-20f7739eb5ff53dad0b5ab2d74817b01R750>
of the plot_nave function should be  'k:'  instead of  'k-'  , right?


Thanks

<https://github.com/vtsuperdarn/davitpy/issues/120>

**Comment by ksterne** [comment]
I agree here with @MuhammadVT , it seems as though this is fixed in #149.
