### ISSUE TITLE
Can't get scans from radDataPtr, what am I doing wrong?

### ISSUE THREAD

**Issue by cmeeren** [vtsuperdarn/davitpy#181]
I can't figure out why this isn't working. I know there is supposed to be data from this time.

```
Python 2.7.10 |Anaconda 2.1.0 (64-bit)| (default, Oct 19 2015, 18:04:42) 
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: import datetime as dt

In [2]: from davitpy import utils, pydarn
Loaded davitpyrc file from DaViTpy installation directory. Path: /home/christer/.local/lib/python2.7/site-packages/davitpy-0.4-py2.7-linux-x86_64.egg/davitpy
Radars information has been updated.

In [3]: dtStart = dt.datetime(2013, 11, 3, 19, 0)

In [4]: data = pydarn.sdio.radDataRead.radDataOpen(dtStart, 'han', eTime=dtStart+dt.timedelta(hours=1))

Looking locally for fitex files with radcode: han channel: None
could not find fitex data in local files

Looking locally for fitacf files with radcode: han channel: None
could not find fitacf data in local files

Looking locally for lmfit files with radcode: han channel: None
could not find lmfit data in local files

Looking on the remote SFTP server for fitex files
Checking file: /tmp/sd/20131103.1800.01.han.fitex
Checking file: /tmp/sd/20131103.1800.11.han.fitex
Checking file: /tmp/sd/20131103.2001.00.han.fitex
removing invalid file: /tmp/sd/20131103.1800.01.han.fitex
removing invalid file: /tmp/sd/20131103.2001.00.han.fitex
found fitex data on sftp server
Concatenating all the files in to one
cat /tmp/sd/20131103.1800.11.han.fitex > /tmp/sd/20131103.190000.20131103.200000.han.fitex
rm /tmp/sd/20131103.1800.11.han.fitex

In [5]: scan = pydarn.sdio.radDataRead.radDataReadScan(data)

reached end of data

In [6]: type(scan)
Out[6]: NoneType
```

**Comment by asreimer** [comment]
Try another radar. If you do this with Saskatoon for instance, it works perfectly. 

Investigating, I found the problem you had is caused by Hankasalmi having a very odd scan flag structure. For example, here's the scan flag for the first 32 beam records of Saskatoon:

>[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

and here's the first 32 for Hankasalmi:

>[-1, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

So you may wish to ask the Hankasalmi PI what is going on with their scan flags (unless someone here knows why it's like that). Nothing wrong with the davitpy code here.

**Comment by cmeeren** [comment]
Thanks! So how can I plot scans for Hankasalmi then?

**Comment by asreimer** [comment]
You'll have to collect one of each beam into a list. AFAIK, a scanData object is just a list. Han at that time is running CPID 153 though. Here's a list of the first 16 beam record's beam numbers:

> [15, 9, 14, 9, 13, 9, 12, 9, 11, 9, 10, 9, 9, 9, 8, 9]

So look at the pattern and extract what you want. When you say you want to plot a scan, you mean you want to plot a FOV? The fov plotting software isn't flexible enough to handle general cases like this so you'll have to hack something together on your own for now.

**Comment by cmeeren** [comment]
Yes, I'm talking about plotting a FOV. Thanks, I'll try to hack something together myself then. :)

**Comment by ksterne** [comment]
The scan flag being -1 is used by several other radars than just han.  That I know of here is sye, sys, unw, zho.  I wonder if other Leicester radars do the same.... We may want to actually take a look at this.

**Comment by asreimer** [comment]
In @cmeeren's case, the problem isn't that the scan flag is -1, it's that the scan pattern isn't the standard 16 beams in sequence.

Looking at the radDataTypes.py file (specifically [here](https://github.com/vtsuperdarn/davitpy/blob/develop/davitpy/pydarn/sdio/radDataTypes.py#L510-L550)), radars with the standard scan pattern but with -1 for the scan flag instead of 1 will not return a valid scan. 

This is probably an issue, but we should open a new issue for it so this is clear.

**Comment by asreimer** [comment]
I made a new issue https://github.com/vtsuperdarn/davitpy/issues/183 to discuss the -1 scan flag problem.
