### ISSUE TITLE
batch download feature missing

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#298]
fetchUtils is a bit clunky for someone who wants to download a bit of data to use offline in the future and doesn't want to process it immediately.  This can be fixed and should be fixed.

**Comment by ksterne** [comment]
Hey @aburrell,

I'm not sure I understand your issue here.  If you wanted to download a good set of files, then you can set up some nested for loops and repeatedly call `radDataOpen()` which will go and download files to your cache directory.  I guess this defaults to the /tmp/ directory right now which is flushed on most systems whenever the system is rebooted.  But you can change this cache directory to somewhere else so that the files are stored.

**Comment by aburrell** [comment]
You hit upon the main issue, which is the unnecessary overhead of the files being unzipped and concatenated.  This could also introduce an artificial issue for someone that doesn't have a lot of working space.  Both of these are reasons enough to have a downloading script.

**Comment by asreimer** [comment]
We need to be very careful about how we talk about this. We're confusing things in this discussion:

1) fetchUtils can literally be used to download massive amounts of data. [Look at the arguments to fetch_remote_files](https://github.com/vtsuperdarn/davitpy/blob/master/davitpy/pydarn/sdio/fetchUtils.py#L298-L301). In fact, fetchUtils entire raison d'etre is for downloading data. This is __completely__ independent of the file reading. There's absolutely no need to use radDataOpen for fetching data.

So, perhaps to make fetchUtils a bit more user frienldy, a wrapper function for the remote fetching code could be added just for downloading large sets of data. I think this is what @aburrell was implicitly suggesting we do.

2) At the risk of conflating multiple issues: The file reading code overly depends on fetchUtils. The proper thing to do with it is to strip out fetchUtils from the file reading completely. Make the workflow explicitly: a) Download data with fetchUtils if needed, b) pass list of files you want to read/plot/etc to the appropriate piece of davitpy code.

3) An important note: fetchUtils doesn't concatenate the files together. That is done in radDataOpen(). 

4) File reading shouldn't depend on concatenating the files together. I built in support for this in #249. What happens if we switch to hdf5 files for example (we really should... but that's another issue entirely) 

Hopefully this clarifies a few tings.

**Comment by ksterne** [comment]
I think there's another more philosophical problem here as well.  Should we be developing davitpy to be a data downloading software?  I thought it was a way to plot data and the file downloading is an extra feature.  I think as I've heard @ajribeiro tell it, file caching wasn't in the first inception of davitpy, but was added for users that have a slow internet connection.

If you're wanting a big batch of data to take with you somewhere, isn't it better to contact @kevinkrieger at University of Saskatchewan or Paul Breen at BAS to get an account with a data mirror?  I think for the case of USask, it more so getting an account with globus.  But that way you could download big batches of data with rsync, sftp, or scp that fetchUtils is just a python wrapper for?

**Comment by asreimer** [comment]
Ya @ksterne I mostly agree with you on this.

While it would be ideal to support batch downloading of files, it really is a pain to support everyone's different archive formats. Perhaps we should just focus on getting the rest of the codebase polished up? We need to be careful though @ksterne because we are both from institutes that maintain a copy of all SuperDARN data. Are we the rule or the exception?

The question really boils down to:
1) Do people normally have access to big batches of SuperDARN data at their institute?
or
2) Do people normally have to download big batches of SuperDARN data before working on it? Where from and how do they get this data?

**Comment by asreimer** [comment]
And ya, fetchUtils is really just a clever (almost too clever...) wrapper for sftp right now.

**Comment by ksterne** [comment]
Has there been anymore thoughts on this?  Still not sure that enabling davitpy as more of a data downloader is good.  This is something we've thought about in the data distribution WG.  I do get your point @asreimer that we are/were apart of institutions that had large archives.  But, there are several ways to download data.

**Comment by aburrell** [comment]
Thanks for the clear summary @asreimer.  I think we should aim to separate data downloading from data reading (perhaps as a submodule of sdio) to allow downloading to occur during the night and data reading occur during the day.  I think this will be especially helpful for new users at institutions without a local superDARN database who are just learning python and don't yet have a handle on rsync, etc.

I don't think we need to worry about support for everyone's archive formats.  The input options in fetchUtils and the defaults in davitpyrc can be set to overcome this.  We just need to improve our documentation to make this clearer.

I also don't think this is the highest priority.  But I think it is functionality that would make SuperDARN more accessible to the larger space physics community.

**Comment by ksterne** [comment]
Some of the issues presented here lead to the "closing" of the sftp server that was being used by davitpy.  I don't think there was any movement on improving `fetchUtils` though.  Closing this issue for deprecating of this repo.
