### ISSUE TITLE
FITEX vs FITEX2

### ISSUE THREAD

**Issue by ReedOnly** [vtsuperdarn/davitpy#308]
Hi,

I'm doing some error investigation with the autocorrelation functions used to determine the Doppler velocity of the SuperDARN radars. After reading [A comparison of SuperDARN ACF ﬁtting methods, [Ribeiro, 2013]](http://onlinelibrary.wiley.com/doi/10.1002/rds.20031/full) it becomes clear that there is three fitting algorithms currently used; FITACF, FITEX2 and LMFIT. On the Virginia Tech sites it can be chosen between FIT, FITEX and FITACF. In DaViTpy the options are FITEX, FITACF and LMFIT. My question is, is the FITEX used in DaViTpy and on Virginia Tech sites actually the improved FITEX2 algorithm described in the paper, or the older FITEX method?

If it turns out to be the older one, this is not included in the AFC fitting tool http://vt.superdarn.org/tiki-index.php?page=ACF+Plotting+Tools.

Hope anyone knows this!

Cheers,
Kristian Reed

**Comment by asreimer** [comment]
Hey @ReedOnly 

VT uses FITEX2 algorithm. @ksterne can confirm.

I'm working on getting a paper published right now that describes the difficulties with fitting SuperDARN ACFs and the proper way to fit them. This topic is my PhD thesis. It turns out that the best way is actually along the lines of LMFIT, but you need to do a good job of estimating the variance of the ACFs (FITACF, FITEX2 and LMFIT do not do this very well). When you estimate the variances properly, we recover ~50% more data when fitting the ACFs compared to what FITACF obtains. And the errorbars on the fitted parameters make sense. I have a presentation that will be given by my supervisor at the SuperDARN workshop on this.

If you are interested, I've put some fitting software on github that uses the methodology described in my papers here: https://github.com/asreimer/lmfit2 The software has been tested on 8 years of Saskatoon SuperDARN data, but there could be some bugs in there. Also, it doesn't yet do fits for elevation angles. I'm waiting on coauthors and will be submitting the paper hopefully before June.

**Comment by asreimer** [comment]
If you want to discuss the velocity errors in more detail, send me an email and we can set up a Skype conversation! :)

**Comment by ReedOnly** [comment]
Hey! Sorry for late reply!

Thank you so much for your clarification :) I'm handing in my master thesis about reversed flows seen by SuperDARN data in a few weeks. I think I got what I need, and (luckily) the technical aspects of ACF is not the main importance of my thesis. Anyways, I realized the reason FITACF produces wrong reversed flows is because of an initial guess based on the first lags, which FITEX and LMFIT does not use.

-Kristian

**Comment by asreimer** [comment]
It's more than just an incorrect initial guess.

The way cross range interference (known in radar as self-clutter) is handled in FITACF (and FITEX and LMFIT) is that "bad" lags are detected and thrown away. They aren't used to fit the ACF. When you don't have all the lags, sometimes the phase unwrapping will unwrap the phase in the wrong direction!

Think about a car tire spinning. When you watch it, it can sometimes look like it's spinning backwards even if it isn't. That's because we aren't sampling fast enough to resolve an ambiguity in the rotation rate.

Good luck with your thesis!

**Comment by asreimer** [comment]
I should add that FITEX2 doesn't actually unwrap the phase so it doesn't run in to this problem. LMFIT is based on FITEX2 so it also doesn't have this problem.
