### ISSUE TITLE
remove local AACGM and use python module

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#350]
I've been working with Simon (and building off of @cmeeren's module) to make an official python version of AACGM-V2.  I have an updated release out now, so it's up-to-date with the current davitpy version of the model.

It would be in the scope of trimming davitpy and simplify the places I (or others) have to go to update the code to remove the davitpy implementation of AACGM and import this one.

Questions, comments, thoughts, opinions?

**Comment by aburrell** [comment]
Added bonus: new version is python3 compatible and works on windows.  The davitpy version isn't and doesn't.

**Comment by johncoxon** [comment]
This would also be pleasing because the davitpy implementation of AACGM has some odd quirks:

1. In `aacgmv2`, you can pass arrays or single values of latitudes and longitudes without issue, whereas in davitpy, you have to switch from `get_aacgm_coord` to `get_aacgm_coord_arr`.
2. In `aacgmv2`, you can pass a single value for altitude and it'll realise all your coordinates are to be evaluated at that altitude. In davitpy, you have to specify an array of altitudes, and if you don't it is **non-trivial** to work out why your call is failing.
3. In davitpy, passing lists is okay but passing tuples is not, which would need fixing if the davitpy team did decide to keep the local AACGM implementation.

**Comment by ksterne** [comment]
Whoops, not sure how that unassigned happened.  Regardless closing this issue as this repo is being deprecated.  Great job @aburrell on getting a stand-alone AACGMv2 python wrapper!
