### ISSUE TITLE
doi

### ISSUE THREAD

**Issue by aburrell** [vtsuperdarn/davitpy#357]
Apparently zenodo won't let me create a doi for repositories not in aburrell (not as advanced as travis-ci).  @ksterne , do you have the most permissions here?  You might need to do this.

**Comment by ksterne** [comment]
So, I think I was able to do this...but I think something's off since I wasn't creating a new release.  I manually uploaded the 0.8 zip-ball and it's at: http://doi.org/10.5281/zenodo.1288637 . At least I think so.  Can you confirm this?  I know support for davitpy is nearing and end, but maybe it's about time to do a 0.9 release to see if this is setup correctly now?

**Comment by asreimer** [comment]
Looks good to me @ksterne!
