### ISSUE TITLE
what should I do if I only want to download the SuperDARN data of fitacf level?

### ISSUE THREAD

**Issue by Guojun-li** [vtsuperdarn/davitpy#370]
I have installed the davitpy, there are so many functions in the folder, but what I want is just to download the SuperDARN data of fitacf level. Are there any solution to my problem? I have struggled with it for hours, I would appreciate it if anyone could give me a hand.

**Comment by aburrell** [comment]
The reading and loading functions in `davitpy.pydarn.sdio` are what you want.  What have you tried and what errors are you getting?

**Comment by asreimer** [comment]
Hi @Guojun-li,

Following the example (slightly modified here) in our tutorial jupyter notebook [here](https://github.com/vtsuperdarn/davitpy/blob/master/docs/notebook/radDataRead.ipynb), if you wanted to download some fitacf data for 10 June 2012 for the Saskatoon radar:

    from datetime import datetime
    from davitpy import pydarn
    
    sTime = datetime(2012,6,10)
    eTime = datetime(2012,6,11)
    rad = 'sas'
    bmnum = 7
    fileType = 'fitacf'
    
    myPtr = pydarn.sdio.radDataOpen(sTime,rad,eTime=eTime,bmnum=bmnum,fileType=fileType,src='sftp')

This will search the Virginia Tech server for all fitacf data that matches the requested time and download the files. It will then concatenated them all together and provide a pointer to the concatenated file via `myPtr`.

To read a record from the concatenated file:

    myBeam = pydarn.sdio.radDataReadRec(myPtr)

**Comment by ksterne** [comment]
I should probably let a cat out of the bag here:

> This will search the Virginia Tech server for all fitacf data that matches the requested time and download the files.

About a month and a half ago, I broke the sftp server that davitpy is using to access data at VT.  So, if the goal here is to download fitacf-level files using the sftp server that davitpy was using, then this will no longer work.  If this is the goal, then please e-mail me (you can find [my address here](http://vt.superdarn.org/tiki-index.php?page=Personnel)) or post your e-mail address and I can address distributing files to you.

Otherwise, if the goal is not to download data, then please post the error messages and code your using to access data as @aburrell and @asreimer have noted.

**Comment by asreimer** [comment]
Any ETA on when that server will be back up and running @ksterne? There are several ongoing projects that were and plan to continue using it. If not, alternatives?

**Comment by ksterne** [comment]
Sorry for the slow response here, @asreimer, there isn't any immediate timeline on when things will be up and running again.  Maybe this will be discussed in early June during the Workshop.  It would be helpful if you could send me what projects that are or were using this SuperDARN data access.  Otherwise, as I noted before, the immediate alternative is to e-mail me for what data you would like.
